version: '3'
services:
  my-great-nginx-web-server:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./
        target: /usr/share/nginx/html/
    restart: always